[nitpick.styles]
include = ["ruff", "mkdocs", "pre-commit"]

[nitpick.files.present]
#".editorconfig" = ""
#".pre-commit-config.yaml" = "Create the file with the contents below, then run 'pre-commit install'"

["pyproject.toml".uv]
package = true
