
#
# .pre-commit-config.yaml
#
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v5.0.0"
[[".pre-commit-config.yaml".repos.hooks]]
id = "end-of-file-fixer"
[[".pre-commit-config.yaml".repos.hooks]]
id = "trailing-whitespace"

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/adamchainz/djade-pre-commit"
rev = "1.3.2"
[[".pre-commit-config.yaml".repos.hooks]]
id = "djade"
args = ["--target-version", "5.1"]

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.8.4"
[[".pre-commit-config.yaml".repos.hooks]]
id = "ruff"
[[".pre-commit-config.yaml".repos.hooks]]
id = "ruff-format"
args = ["--check"]

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/saxix/pch"
rev = "v0.1"
[[".pre-commit-config.yaml".repos.hooks]]
id = "check-missed-migrations"
args = ["src"]
stages = [ "pre-commit" ]
additional_dependencies= [ "setuptools" ]
